import prisma from "@/lib/prisma";
import { NextRequest, NextResponse } from "next/server";
import { generateKHSet } from "@/lib/kh-generator";
import { LLMProvider } from "@/lib/llm";
import { getRequiredUser, isAdmin } from "@/lib/auth-helpers";
import { campaignCreateSchema, parseBody } from "@/lib/validations";
import {
  SUBSCRIPTION_TIERS,
  type SubscriptionTier,
} from "@/lib/subscription-tiers";

export async function GET() {
  const user = await getRequiredUser();

  const campaigns = await prisma.campaign.findMany({
    where: { userId: user.id },
    orderBy: { createdAt: "desc" },
    include: { _count: { select: { khSets: true, documents: true } } },
  });
  return NextResponse.json(campaigns);
}

export async function POST(req: NextRequest) {
  const user = await getRequiredUser();

  const raw = await req.json();
  const parsed = parseBody(campaignCreateSchema, raw);
  if (!parsed.success) {
    return NextResponse.json({ error: parsed.error }, { status: 400 });
  }
  const body = parsed.data;

  // Enforce campaign limit per tier (admins bypass all limits)
  if (!isAdmin(user)) {
    const tier = user.plan as SubscriptionTier;
    const tierConfig = SUBSCRIPTION_TIERS[tier];
    if (tierConfig.maxCampaigns !== -1) {
      const count = await prisma.campaign.count({ where: { userId: user.id } });
      if (count >= tierConfig.maxCampaigns) {
        return NextResponse.json(
          { error: `Campaign limit reached (${tierConfig.maxCampaigns} for ${tierConfig.label} plan). Upgrade to create more.` },
          { status: 403 }
        );
      }
    }
  }

  // Create campaign with optional document in a single transaction
  let campaign;
  try {
    campaign = await prisma.$transaction(async (tx) => {
      const c = await tx.campaign.create({
        data: {
          userId: user.id,
          name: body.name,
          marketingGoal: body.marketingGoal,
          brandNiche: body.brandNiche,
          targetAudienceAge: body.targetAudienceAge,
          targetLocation: body.targetLocation,
          audienceInterests: body.audienceInterests,
          minFollowers: body.minFollowers,
          minEngagementRate: body.minEngagementRate ?? 3,
          numberOfInfluencers: body.numberOfInfluencers ?? 25,
          targetKeywords: body.targetKeywords ?? 10,
          targetHashtags: body.targetHashtags ?? 10,
          targetLeads: body.targetLeads ?? 2000,
          trendingTopics: body.trendingTopics,
          competitorBrands: body.competitorBrands,
          additionalKeywords: body.additionalKeywords,
        },
      });

      // If a document was analyzed during creation, attach it
      if (body.documentContent && body.documentFilename) {
        await tx.document.create({
          data: {
            campaignId: c.id,
            filename: body.documentFilename,
            mimeType: body.documentMimeType || "text/plain",
            content: body.documentContent,
          },
        });
      }

      return c;
    });
  } catch (err) {
    console.error("[campaign-create] Transaction failed:", err);
    return NextResponse.json(
      { error: "Failed to create campaign. Please try again." },
      { status: 500 }
    );
  }

  // Auto-generate first KH set if a document was provided (outside transaction — LLM calls are slow)
  if (body.documentContent) {
    try {
      const provider: LLMProvider = body.provider ?? "openai";
      const targetKw = body.targetKeywords ?? 10;
      const targetHt = body.targetHashtags ?? 10;

      const khSet = await generateKHSet({
        campaignId: campaign.id,
        campaign,
        documentContents: [body.documentContent],
        minKeywords: targetKw,
        maxKeywords: targetKw,
        minHashtags: targetHt,
        maxHashtags: targetHt,
        provider,
        userId: user.id,
      });

      return NextResponse.json(
        { ...campaign, autoGeneratedKhSetId: khSet.id },
        { status: 201 }
      );
    } catch (err) {
      // KH generation failed — still return the campaign, just without auto-generated set
      console.error("[campaign-create] Auto KH generation failed:", err);
      return NextResponse.json(campaign, { status: 201 });
    }
  }

  return NextResponse.json(campaign, { status: 201 });
}
